name: pizza_repository
description: A new Flutter package for pizza repository.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7


  # cloud_firestore: ^4.17.5 # Pizza data များကို Firestore မှ ယူမည်ဆိုပါက ဖွင့်သုံးပါ

  # State Management & Utilities
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Local Package Dependency
  user_repository:
    path: ../user_repository # 👈 လမ်းကြောင်း အမှန်

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true